### ISSUE TITLE
[enhancements] friction logs for `Download repositories.ipynb`

### ISSUE THREAD

**Issue by EgorBu** [mloncode/devfest2019-workshop#10]
I launched it without docker - so probably it wouldn't be an issue in case of docker.
But I think ideally it should be possible to launch notebooks itself after installing dependencies.

Logs:
* create dir "output" in "notebook" dir
* `!cd /devfest/repos && git clone -q {clone_url}` - make it not absolute path to make it easy launchable from notebook (and probably create another dir)

**Comment by m09** [comment]
Let's close this one and address in repo for next workshop!
