### ISSUE TITLE
Start presentation discussion

### ISSUE THREAD

**Issue by m09** [mloncode/devfest2019-workshop#7]
We can have from 10 to 20 min for the initial presentation, depending on what we want to cover.

Suggestions that were discussed:
 - cover ML on Code: analogy to NLP, datasets, challenges etc
 - briefly cover good project process: problem statement, exploration, evaluation, etc
 - 

TODOs:
 - [x] a shared googleDoc with the titles
 - [x] apply some doc template (either conference one, or company one)
 - [ ] add bullet points to each slide
 - [ ] improve and polish
 - [ ] Put agenda before each section

**Comment by bzz** [comment]
Here is an [initial attempt](https://docs.google.com/presentation/d/1vF0JMagmXXzn-h-OaJu6CsDt78oSQSg58YFJsBUaHxk/edit#slide=id.g63f2f7a940_0_200) of putting together a slide deck ridge.

**Comment by m09** [comment]
Slides are [up](https://docs.google.com/presentation/d/1vF0JMagmXXzn-h-OaJu6CsDt78oSQSg58YFJsBUaHxk/edit)
